name: Build Github Pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Set up Cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/**.yml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install MkDocs
      run: |
        pip install mkdocs mkdocs-material
        pip install pygments pymdown-extensions
        pip install mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin
    - name: Build Site
      run: mkdocs build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@2.0.0
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: site
